import {useEffect, useState} from 'react'

import Head from 'next/head'

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Divider from '@mui/material/Divider';
import Grid from '@mui/material/Grid';

import List from '@mui/material/List';

import Table from '@mui/material/Table';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';

import Typography from '@mui/material/Typography';
import Paper from '@mui/material/Paper';

import Navbar from '../components/Navbar'
import AuthorInfo from '../components/AuthorInfo';
import BooksTable from '../components/BooksTable';
import PopularAuthorList from '../components/PopularAuthorList';

import { POPULAR_AUTHORS } from '../utils/constants/popular_authors';
import { getAuthor } from '../utils/api/authors';
import { getAuthorWorks } from '../utils/api/authors';

export default function Home() {
  const [authorKey, setAuthorKey]= useState("OL23919A")
  const [authorData, setAuthorData] = useState("OL23919A")
  const [authorWorks, setAuthorWorks] = useState([])

  // get the Author's information data everytime the author key is changed
  useEffect(()=>{
    // console.log(authorKey)
    getAuthor(authorKey).then((data)=>{
      // console.log(data)
      setAuthorData(data)
    })
  },[authorKey])

  // get the Author's works when the author key is changed:
  useEffect(()=>{
    getAuthorWorks(authorKey).then((data)=>{
      // console.log(data)
      setAuthorWorks(data.entries)
    })
  },[authorKey])

    const changeAuthorKey = (authorId)=>{
      setAuthorKey(authorId)
      // console.log(authorId)
    }

  return <>
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <Box>
                <AuthorInfo
                name={authorData.name}
                birthDate={authorData.birth_date}
                deathDate={authorData.death_date}
                />
                <TableContainer component={Paper}>
                  <Table>
                    <TableHead>
                        <TableRow>
                        <TableCell>Books in all Languages</TableCell>
                        </TableRow>
                    </TableHead>
                    {authorWorks.map((book)=>{
                      return <BooksTable
                        key={book.key}
                        title={book.title}
                      />
                    })}
                  </Table>
                </TableContainer>
              </Box>
            </Grid>
            <Grid item xs={4}>
              
              <Box sx={{width: '100%'}}>
                <Typography
                  component="h1"
                  variant="h4"
                  align="center"
                  color="text.primary"
                  gutterBottom
                >
                  Popular Authors
                </Typography>
                <List sx={{width: '100%'}}>
                  <Divider />
                  {POPULAR_AUTHORS.map((author, index)=>{
                    return <PopularAuthorList
                      name={author.name}
                      key={index}
                      id={author.key}
                      changeAuthorKeyCallback={changeAuthorKey}
                      />
                  })

                  }
                  
                </List>
              </Box>
            </Grid>
          </Grid>
          
        </Container>
      </main>
    </div>
  </>
}
